"""
Streamlit Dashboard
===================
Interactive web dashboard for visualizing renewable energy
stability forecasts and historical data exploration.
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

import streamlit as st
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go

st.set_page_config(
    page_title="Renewable Stability Forecasting",
    page_icon="⚡",
    layout="wide",
)

st.title("Renewable Integration Stability Forecasting")
st.markdown("**Northern Ireland -- NASA POWER 10-Year Hourly Data (2015-2025)**")

# -- Sidebar ----------------------------------------------------
st.sidebar.header("Navigation")
page = st.sidebar.radio(
    "Select Page",
    ["Overview", "Exploratory Data Analysis", "Risk Analysis", "Deep Learning", "Interactive Forecast"]
)

# -- Load Data --------------------------------------------------
@st.cache_data
def load_data():
    # Load a sample for visualization if available
    try:
        from config.spark_config import CLEAN_DATA_DIR
        feat_path = CLEAN_DATA_DIR / "nasa_power_features"
        if feat_path.exists():
            # Read parquet using pandas (requires pyarrow)
            return pd.read_parquet(feat_path)
    except Exception:
        pass
    return None

df = load_data()

# -- Page: Overview ---------------------------------------------
if page == "Overview":
    st.header("Project Overview")
    st.markdown("""
    This dashboard provides real-time visualization of renewable energy 
    integration stability for Northern Ireland, using 10 years of hourly 
    meteorological data from NASA POWER.
    
    **Key Features:**
    - Wind Power Index (WPI) monitoring
    - Solar Irradiance Index (SII) tracking
    - Renewable Volatility Stress Index (RVSI) 
    - [WARNING] Grid instability risk classification
    - 624-hour ahead forecasting
    """)
    
    if df is not None:
        st.success(f"Loaded {len(df):,} records from pipeline.")
        st.dataframe(df.head())
    else:
        st.info("Run the data pipeline to populate the dashboard.")

# -- Page: EDA --------------------------------------------------
elif page == "Exploratory Data Analysis":
    st.header("Exploratory Data Analysis")
    st.markdown("Visualizations generated by the EDA pipeline.")
    
    tab1, tab2, tab3, tab4 = st.tabs(["Distributions", "Trends", "Correlations", "Seasonality"])
    
    with tab1:
        st.image("data/plots/02_distributions.png", caption="Variable Distributions")
        st.image("data/plots/07_wind_direction.png", caption="Wind Direction")
    
    with tab2:
        st.image("data/plots/04_time_series_trends.png", caption="10-Year Trends")
        st.image("data/plots/05_hourly_patterns.png", caption="Diurnal Patterns")
        
    with tab3:
        st.image("data/plots/03_correlation_heatmap.png", caption="Correlation Matrix")
        st.image("data/plots/12_wpi_vs_sii_scatter.png", caption="WPI vs SII Scatter")
        
    with tab4:
        st.image("data/plots/06_seasonal_boxplots.png", caption="Seasonal Distributions")
        st.image("data/plots/09_seasonal_decomposition.png", caption="STL Decomposition")

# -- Page: Risk Analysis ----------------------------------------
elif page == "Risk Analysis":
    st.header("Renewable Volatility & Risk")
    
    if df is not None:
        st.subheader("RVSI Distribution")
        st.image("data/plots/11_rvsi_analysis.png")
        
        st.subheader("Historical Risk Timeline")
        # Simple timeline plot of RVSI
        st.line_chart(df.set_index("timestamp")["rvsi"].tail(500))
    else:
        st.info("Pipeline output not found.")

# -- Page: Deep Learning ----------------------------------------
elif page == "Deep Learning":
    st.header("Deep Learning Results")
    
    col1, col2 = st.columns(2)
    with col1:
        st.subheader("LSTM (RVSI Forecasting)")
        st.image("data/plots/13_lstm_regression.png")
    
    with col2:
        st.subheader("DNN (Risk Classification)")
        st.image("data/plots/14_dnn_classification.png")
        
    st.subheader("Time Series (SARIMA)")
    st.image("data/plots/15_sarima_forecast.png")

# -- Page: Forecast ---------------------------------------------
elif page == "Interactive Forecast":
    st.header("Interactive Forecast")
    st.markdown("Enter meteorological parameters to get a stability forecast.")
    
    col1, col2 = st.columns(2)
    with col1:
        wind_speed = st.slider("Wind Speed at 50m (m/s)", 0.0, 35.0, 7.0)
        temperature = st.slider("Temperature (C)", -10.0, 30.0, 10.0)
        cloud_cover = st.slider("Cloud Cover (%)", 0.0, 100.0, 70.0)
    with col2:
        solar_irr = st.slider("Solar Irradiance (Wh/m2)", 0.0, 900.0, 200.0)
        air_density = st.slider("Air Density (kg/m3)", 1.0, 1.4, 1.23)
        humidity = st.slider("Relative Humidity (%)", 30.0, 100.0, 85.0)
    
    if st.button("Predict Stability", type="primary"):
        # Simple rule-based proxy until model is loaded
        wpi = 0.5 * air_density * (wind_speed ** 3)
        sii = solar_irr * (1 - cloud_cover/100)
        rvsi_proxy = (wpi * 0.6 + sii * 0.4) / 1000  # Simplified scaling
        
        st.metric("Estimated WPI", f"{wpi:.2f}")
        st.metric("Estimated SII", f"{sii:.2f}")
        st.metric("Predicted RVSI (Proxy)", f"{rvsi_proxy:.4f}")
        
        if rvsi_proxy > 1.5:
            st.error("Risk Level: CRITICAL")
        elif rvsi_proxy > 1.0:
            st.warning("Risk Level: HIGH")
        elif rvsi_proxy > 0.5:
            st.info("Risk Level: MEDIUM")
        else:
            st.success("Risk Level: LOW")
